---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-fhir-server
  name: clin-fhir-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clin-fhir-server
  template:
    metadata:
      labels:
        app: clin-fhir-server
    spec:
      containers:
        - image: chusj/clin-fhir-server:__UNDEFINED__
          name: clin-fhir-server
          resources:
            requests:
              memory: "1024Mi"
              cpu: '1.00'
            limits:
              memory: "2048Mi"
              cpu: '2.00'
          envFrom:
            - configMapRef:
                name: clin-fhir-server
          env:
            - name: HAPI_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: clin-fhir-db-credentials
                  key: username
            - name: HAPI_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clin-fhir-db-credentials
                  key: password